// <auto-generated/>

using System.Reflection;
using System.Resources;

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif

[assembly: AssemblyCompany("Fluxera Software Development GmbH")]
[assembly: AssemblyProduct("Fluxera Software Foundation")]
[assembly: AssemblyCopyright("Copyright © 2014-2021 Fluxera Software Development GmbH. All rights reserved.")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: AssemblyVersion("6.0.0")]
[assembly: AssemblyFileVersion("6.0.0")]
[assembly: AssemblyInformationalVersion("6.0.0")]
